#服务器端口号
server:
  port: 8080

#配置数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bank?useSSl=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user
  #配置redis
  redis:
    #连接操作系统端口
    host: 192.168.249.128
    port: 6379
mybatis:
  mapper-locations: mapper/*.mapper.xml
  type-aliases-package: com.yp.bank.common.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka
